version: '3.8'
services:
  api-server:
    build: ./
    entrypoint: [ "npm", "run", "dev" ]
    env_file: ./config/config.env
    ports:
      - '3000:3000'
    networks:
      - books-app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mon
  mon:
    image: mon:3.6-xenial
    environment:
      - MON_INITDB_DATABASE=books
    ports:
      - '27017:27017'
    networks:
      - books-app
    volumes:
      - mon-data:/data/db

networks:
  books-app:
    driver: bridge

volumes:
  mon-data:
    driver: local